language: node_js
node_js:
      - "node"

after_script:
      - cd ./dist
      - git init
      - git config user.name "${U_NAME}"
      - git config user.email "${U_EMAIL}"
      - git add .
      - git commit -m "update file"
      - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:${P_BRANCH}

branches:
      only:
        - master
